name: bedrock_edition_protocol
description: A library that allows you to obtain basic information from a Minecraft Bedrock Edition server.
version: 1.0.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  convert: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
